name: interop
version: 0.1.0.0
synopsis: Foreign function calls to Haskell
description: Please see the README at <https://github.com/jwoudenberg/interop>.
author: Jasper Woudenberg
maintainer: mail@jasperwoudenberg.com
copyright: 2020 Jasper Woudenberg
homepage: https://github.com/jwoudenberg/interop#readme
license-file: LICENSE
category: Web
github: jwoudenberg/interop
extra-doc-files:
- README.md
- CHANGELOG.md
library:
  dependencies:
  - aeson >= 1.2.4.0 && < 1.6
  - base >= 4.10.1.0 && < 5
  - bytestring >= 0.10.8.2 && < 0.12
  - scientific >= 0.3 && < 0.4
  - text >= 1.2.3.0 && < 1.3
  - unordered-containers >= 0.2.0.0 && < 0.3
  - wai >= 3.2.0 && < 3.3
  exposed-modules:
  - Interop
  - Interop.Ruby
  source-dirs: src
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wredundant-constraints
- -Wincomplete-uni-patterns
