name: interop
version: 0.1.0.0
synopsis: Foreign function calls to Haskell
description: Please see the README at <https://github.com/jwoudenberg/interop>.
author: Jasper Woudenberg
maintainer: mail@jasperwoudenberg.com
copyright: 2020 Jasper Woudenberg
homepage: https://github.com/jwoudenberg/interop#readme
license-file: LICENSE
category: Web
github: jwoudenberg/interop
extra-doc-files:
- README.md
- CHANGELOG.md
library:
  dependencies:
  - base >= 4.10.1.0 && < 5
  source-dirs: src
