name: interop
version: 0.1.0.0
synopsis: Foreign function calls to Haskell
description: Please see the README at <https://github.com/jwoudenberg/interop>.
author: Jasper Woudenberg
maintainer: mail@jasperwoudenberg.com
copyright: 2020 Jasper Woudenberg
homepage: https://github.com/jwoudenberg/interop#readme
license-file: LICENSE
category: Web
github: jwoudenberg/interop
extra-source-files:
- test/**/*.rb
- test/example-compile-errors/*.hs
extra-doc-files:
- README.md
- CHANGELOG.md
library:
  exposed-modules:
  - Interop
  source-dirs: src
executables:
  interop-compatible:
    dependencies:
    - interop
    main: Main.hs
    source-dirs: interop-compatible
tests:
  tests:
    dependencies:
    - aeson-pretty >= 0.8.0 && < 0.9
    - directory >= 1.3.3.0 && < 1.4
    - filepath >= 1.4.0.0 && < 1.5
    - ghc >= 8.8 && < 9.1
    - ghc-paths >= 0.1 && < 0.2
    - hedgehog >= 1.0 && < 1.1
    - process >= 1.6.0.0 && < 1.7
    - warp >= 3.3.0 && < 3.4
    source-dirs:
    - src
    - test
    ghc-options:
    - -threaded
    - -rtsopts "-with-rtsopts=-N -T"
    main: Main.hs
dependencies:
- aeson >= 1.2.4.0 && < 1.6
- base >= 4.10.1.0 && < 5
- bytestring >= 0.10.8.2 && < 0.12
- containers >= 0.6.0.1 && < 0.7
- unordered-containers >= 0.2.10.0 && < 0.3
- scientific >= 0.3 && < 0.4
- text >= 1.2.3.0 && < 1.3
- wai >= 3.2.0 && < 3.3
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
default-extensions:
- DeriveGeneric
- GeneralizedNewtypeDeriving
- NamedFieldPuns
- OverloadedStrings
- ScopedTypeVariables
- StrictData
